[LightDM]
start-default-seat=true
logind-check-graphical=false

[Seat:*]
autologin-user=beamconsole
autologin-user-timeout=0
autologin-session=xfce
user-session=xfce
greeter-hide-users=true
greeter-show-manual-login=false
allow-user-switching=false
allow-guest=false
